### ISSUE TITLE
KeyError when running

### ISSUE THREAD

**Issue by urschrei** [Nikoleta-v3/blackbook#23]
$ python --version
    Python 3.7.1
    $ pip install blackbook
    [snipped, installs 0.0.2]
    $ ls
    venv/ notebook.ipynb
    $ blackbook .
    Traceback (most recent call last):
      File "/Users/sth/dev/CCA_mining/venv/bin/blackbook", line 11, in <module>
        load_entry_point('blackbook==0.0.2', 'console_scripts', 'blackbook')()
      File "/Users/sth/dev/CCA_mining/venv/lib/python3.7/site-packages/blackbook/__main__.py", line 17, in main
        nb = blackbook.format_notebook_content(notebook_path)
      File "/Users/sth/dev/CCA_mining/venv/lib/python3.7/site-packages/blackbook/__init__.py", line 22, in format_notebook_content
        for cell in nb["cells"]:
    KeyError: 'cells'

**Comment by daffidwilde** [comment]
Hi @urschrei,

Would you mind sharing the raw contents of the `notebook.ipynb` file here. Then I can have a look into recreating the issue.

Thanks

**Comment by urschrei** [comment]
Sure: https://gist.githubusercontent.com/urschrei/c29f10979ac1f31da1017634001881b1/raw/f1e4ca346476e91ba2afeb738b4efd9a9f3b5544/notebook.ipynb

**Comment by daffidwilde** [comment]
I've just recreated this locally. If you run `blackbook notebook.ipynb`, there shouldn't be an error. However, there is something on your end -- likely inside of `venv/` that is being picked up.

We're keen to figure out what that is. Would you mind running the above command and checking there is no error?

**Comment by urschrei** [comment]
Yep, confirmed that it works when run against the notebook!

**Comment by drvinceknight** [comment]
Can you check if you have any `.ipynb` files in any subdirectory?

We actually had previously a check for `KeyError` but removed it because we didn't think it was necessary, it could be worth reverting that but would be great to have any notebook that could show us why it's needed.

**Comment by urschrei** [comment]
Ah, thanks! I did check, and there are notebooks in `venv`, installed by Jupyter / Matplotlib:

    ./.ipynb_checkpoints/notebook-checkpoint.ipynb
    ./venv/lib/python3.7/site-packages/nbformat/tests/test3.ipynb
    ./venv/lib/python3.7/site-packages/nbformat/tests/test4.ipynb
    ./venv/lib/python3.7/site-packages/nbformat/tests/test2.ipynb
    ./venv/lib/python3.7/site-packages/nbformat/tests/test4plus.ipynb
    ./venv/lib/python3.7/site-packages/nbformat/tests/test4custom.ipynb
    ./venv/lib/python3.7/site-packages/nbformat/tests/test4jupyter_metadata.ipynb
    ./venv/lib/python3.7/site-packages/nbformat/tests/test4docinfo.ipynb
    ./venv/lib/python3.7/site-packages/nbformat/tests/invalid.ipynb
    ./venv/lib/python3.7/site-packages/matplotlib/backends/web_backend/nbagg_uat.ipynb
    ./venv/lib/python3.7/site-packages/nbconvert/preprocessors/tests/files/SVG.ipynb
    ./venv/lib/python3.7/site-packages/nbconvert/preprocessors/tests/files/Disable Stdin.ipynb
    ./venv/lib/python3.7/site-packages/nbconvert/preprocessors/tests/files/update-display-id.ipynb
    ./venv/lib/python3.7/site-packages/nbconvert/preprocessors/tests/files/Inline Image.ipynb
    ./venv/lib/python3.7/site-packages/nbconvert/preprocessors/tests/files/Interrupt.ipynb
    ./venv/lib/python3.7/site-packages/nbconvert/preprocessors/tests/files/Factorials.ipynb
    ./venv/lib/python3.7/site-packages/nbconvert/preprocessors/tests/files/Skip Exceptions with Cell Tags.ipynb
    ./venv/lib/python3.7/site-packages/nbconvert/preprocessors/tests/files/Clear Output.ipynb
    ./venv/lib/python3.7/site-packages/nbconvert/preprocessors/tests/files/Empty Cell.ipynb
    ./venv/lib/python3.7/site-packages/nbconvert/preprocessors/tests/files/Unicode.ipynb
    ./venv/lib/python3.7/site-packages/nbconvert/preprocessors/tests/files/HelloWorld.ipynb
    ./venv/lib/python3.7/site-packages/nbconvert/preprocessors/tests/files/Skip Exceptions.ipynb
    ./venv/lib/python3.7/site-packages/nbconvert/exporters/tests/files/notebook2.ipynb
    ./venv/lib/python3.7/site-packages/nbconvert/exporters/tests/files/prompt_numbers.ipynb
    ./venv/lib/python3.7/site-packages/nbconvert/exporters/tests/files/pngmetadata.ipynb
    ./venv/lib/python3.7/site-packages/nbconvert/exporters/tests/files/rawtest.ipynb
    ./venv/lib/python3.7/site-packages/nbconvert/exporters/tests/files/attachment.ipynb
    ./venv/lib/python3.7/site-packages/nbconvert/tests/files/notebook2.ipynb
    ./venv/lib/python3.7/site-packages/nbconvert/tests/files/notebook3_with_errors.ipynb
    ./venv/lib/python3.7/site-packages/nbconvert/tests/files/notebook4_jpeg.ipynb
    ./venv/lib/python3.7/site-packages/nbconvert/tests/files/notebook1.ipynb
    ./venv/lib/python3.7/site-packages/nbconvert/tests/files/markdown_display_priority.ipynb
    ./venv/lib/python3.7/site-packages/nbconvert/tests/files/Widget_List.ipynb
    ./venv/lib/python3.7/site-packages/nbconvert/tests/files/notebook_jl.ipynb
    ./venv/lib/python3.7/site-packages/nbconvert/tests/files/latex-linked-image.ipynb
    ./venv/lib/python3.7/site-packages/notebook/bundler/tests/resources/empty.ipynb

**Comment by drvinceknight** [comment]
At a guess can you share the raw contents of `empty.ipynb` here?

**Comment by urschrei** [comment]
{
      "nbformat_minor": 0,
      "cells": [],
      "nbformat": 4,
      "metadata": {}
    }

**Comment by drvinceknight** [comment]
I've fixed this in https://github.com/Nikoleta-v3/blackbook/pull/24 (which is merged), when @daffidwilde has a moment he'll update the pypi release which should all hopefully work @urschrei but please reopen if it doesn't :+1:
