### ISSUE TITLE
Omit newlines

### ISSUE THREAD

**Issue by azdanov** [Nikoleta-v3/blackbook#25]
Is there a way to prevent the insertion of newlines inside code blocks?

Before: 
<img width="377" alt="screenshot 2019-01-30 at 19 34 16" src="https://user-images.githubusercontent.com/6123841/52000611-40c09c00-24c6-11e9-89f6-48ac32606c96.png">

After:
<img width="349" alt="screenshot 2019-01-30 at 19 34 52" src="https://user-images.githubusercontent.com/6123841/52000619-44542300-24c6-11e9-9c35-7699b33c6818.png">

In the context of a `file.py` it makes sense to have a newline at the end, but here it seems redundant.

**Comment by daffidwilde** [comment]
Hi there,

There is no functionality implemented to do that as we are keen to stick to the black formatting in an uncompromising way to essentially aim to spend no mental energy on formatting. If at some point black added an option to allow that, we would look to include that option in `blackbook`.

**Comment by azdanov** [comment]
@daffidwilde I see. Thanks for answering!

**Comment by ocefpaf** [comment]
> There is no functionality implemented to do that as we are keen to stick to the black formatting in an uncompromising way to essentially aim to spend no mental energy on formatting.

Black does know about notebook cells and treating those as code blocks with a new line is probably not what most notebook users want. I'd open an exception in tour approach there and implement something that removes that new line. The notebook rendering looks silly and "stretched" with those.

**Comment by matthewfeickert** [comment]
@drvinceknight @Nikoleta-v3 @daffidwilde I'd ask that you consider reopening this issue.

As @ocefpaf has pointed out

> Black does know about notebook cells and treating those as code blocks with a new line is probably not what most notebook users want.

the newline here has nothing to do with Black. This can be easily seen by the following example:

```
$ cat spaces.py 
def function(a,b,c):
    return a+b+c
$ black spaces.py 
reformatted spaces.py
All done! ✨ 🍰 ✨
1 file reformatted.
$ cat spaces.py 
def function(a, b, c):
    return a + b + c
```

Here there is no new carriage return inserted at the end of `spaces.py`.

Additionally, if you look at [`tests/data/unformatted/spaces.ipynb`](https://github.com/Nikoleta-v3/blackbook/blob/5fedd349d64001d9fb07fc0f50efd9500e3902f1/tests/data/unformatted/spaces.ipynb) 

![unformattted_spaces](https://user-images.githubusercontent.com/5142394/79421545-a4769e00-7f80-11ea-9523-d1403f34bfa2.png)


and [`tests/data/formatted/spaces.ipynb`](https://github.com/Nikoleta-v3/blackbook/blob/5fedd349d64001d9fb07fc0f50efd9500e3902f1/tests/data/formatted/spaces.ipynb)

![formatted_spaces](https://user-images.githubusercontent.com/5142394/79421552-a8a2bb80-7f80-11ea-9662-2de096a28ce2.png)

there is no new carriage return in [`tests/data/formatted/spaces.ipynb`](https://github.com/Nikoleta-v3/blackbook/blob/5fedd349d64001d9fb07fc0f50efd9500e3902f1/tests/data/formatted/spaces.ipynb). Yet the output of 

```
$ blackbook tests/
2020-04-16 01:25:44.078 | INFO     | blackbook.__main__:main:31 - All done! 📖
2020-04-16 01:25:44.078 | INFO     | blackbook.__main__:main:33 - 1 notebooks reformatted. 3 left unchanged.
```

yields

![spaces_post_format](https://user-images.githubusercontent.com/5142394/79421764-1818ab00-7f81-11ea-845a-1d8f1bafd288.png)


This seems inconsistent, as now the post formatting `tests/data/formatted/spaces.ipynb` is not identical to `tests/data/formatted/spaces.ipynb`, though `blackbook` claims they are

```
$ blackbook tests/
2020-04-16 01:26:54.651 | INFO     | blackbook.__main__:main:31 - All done! 📖
2020-04-16 01:26:54.651 | INFO     | blackbook.__main__:main:33 - 0 notebooks reformatted. 4 left unchanged.
```

**Comment by Nikoleta-v3** [comment]
I am re opening this so we can address @matthewfeickert comment.

**Comment by ocefpaf** [comment]
[This is what](https://github.com/ocefpaf/nbb/blob/38e6630d33e48ebce8217ed47a872214c7e8c7c0/nbb/nbb.py#L27) I done in `nbb` in case you find it useful here.

**Comment by matthewfeickert** [comment]
> [This is what](https://github.com/ocefpaf/nbb/blob/38e6630d33e48ebce8217ed47a872214c7e8c7c0/nbb/nbb.py#L27) I done in `nbb` in case you find it useful here.

That actually is really helpful, as it allows for a much cleaner implementation. Thanks!

```diff
diff --git a/src/blackbook/__init__.py b/src/blackbook/__init__.py
index 73d6ae6..a7b3753 100644
--- a/src/blackbook/__init__.py
+++ b/src/blackbook/__init__.py
@@ -27,12 +27,14 @@ def format_notebook_content(path: pathlib.Path) -> Optional[dict]:
 
                 try:  # Some ipynb files will not have valid source code
                     string = "".join(cell["source"])
-                    formatted_string = black.format_str(string, mode=black.FileMode())
+                    formatted_string = black.format_str(
+                        string, mode=black.FileMode()
+                    ).strip()  # Remove trailing newlines
                     if formatted_string != string:
                         modification_found = True
-                        cell["source"] = [
-                            s + "\n" for s in formatted_string.split("\n")
-                        ][:-1]
+                        cell["source"] = "\n".join(
+                            [line for line in formatted_string.splitlines()]
+                        )
 
                 except black.InvalidInput:
                     pass
```

**Comment by matthewfeickert** [comment]
> I am re opening this so we can address @matthewfeickert comment.

@Nikoleta-v3 If you end up agreeing with the reasoning here of the three of us I have opened up PR #37 that implements this.
