### ISSUE TITLE
Support ability to run blackbook over a single file

### ISSUE THREAD

**Issue by matthewfeickert** [Nikoleta-v3/blackbook#31]
Currently it seems that there is no way to run `blackbook` over a specific file path. Attempting to format a single notebook at path `path/to/notebooks/Example-Notebook.ipynb` fails to do anything

```
$ pip freeze | grep blackbook
blackbook==0.0.5
$ blackbook path/to/notebooks/Example-Notebook.ipynb 
2019-11-29 14:00:14.403 | INFO     | blackbook.__main__:main:25 - All done! 📖
2019-11-29 14:00:14.403 | INFO     | blackbook.__main__:main:27 - 0 notebooks reformatted. 0 left unchanged.
```

where running

```
$ blackbook path/to/notebooks/
2019-11-29 14:05:26.204 | INFO     | blackbook.__main__:main:25 - All done! 📖
2019-11-29 14:05:26.205 | INFO     | blackbook.__main__:main:27 - 1 notebooks reformatted. 0 left unchanged.
```

It would be nice to add support for targeting a single file, in the same way that Black does.

**Comment by drvinceknight** [comment]
Yes, excellent point! This is probably simple to implement. PRs are welcome if you wanted to pick this up @matthewfeickert ? Otherwise I'm sure one of us will at some point.

**Comment by matthewfeickert** [comment]
> PRs are welcome if you wanted to pick this up?

I won't say that I can _actively_ work on this, but given that we want to start using `blackbook` for [`pyhf`](https://github.com/scikit-hep/pyhf) there is a good chance that I might give it a go on a Saturday in a few weeks if no one else has yet.
