### ISSUE TITLE
Make patch release v0.0.6

### ISSUE THREAD

**Issue by matthewfeickert** [Nikoleta-v3/blackbook#39]
Now that @Nikoleta-v3 and @drvinceknight have accepted PR #36 and PR #37 the functionality of `blackbook` has increased/changed enough to probably warrant another patch release. In particular, it would be nice to start to be able to use both these changes in CI pipelines. A `v0.0.6` patch release on both GitHub and PyPI would be very nice.

**Comment by daffidwilde** [comment]
Hi @matthewfeickert thanks for nudging me on this, and thank you for all the work you put in with those PRs.

I'll get on that release now :smile:

**Comment by matthewfeickert** [comment]
> I'll get on that release now

That's fantastic, @daffidwilde! Thank you very much it is really appreciated. Also thank you to you all for making `blackbook`! This tool is great and I'm excited to get it more deeply integrated into my workflow. :)

**Comment by daffidwilde** [comment]
All done! Cheers again and I hope `blackbook` continues to add to your work.
